---
- hosts: all
  gather_facts: False
  vars:
    BASE_DIR: /home/web/spaceawe
    BASE_DIR_LOCAL: "{{ lookup('env','UNAWE_BASE') }}unawe/spaceawe"
    BASE_DIR_EXTRAS: /home/web/django-apps
    BASE_DIR_EXTRAS_LOCAL: "{{ lookup('env','UNAWE_BASE') }}unawe/django-apps"
    VIRTUALENV: /home/web/.virtualenvs/spaceawe
    REPO: https://github.com/unawe/spaceawe.git
    SHORT_NAME: spaceawe
    # STATIC_SITES:
    #   - { cannonical_name: "alpha.space-awareness.org", server_name: "alpha.space-awareness.org alpha.space-awareness.org.local", server_alias: "space-awareness.org" }
    LOG_DIR: /home/web/usr/log
    ETC_DIR: /home/web/usr/etc
  tasks:

    ## PostgreSQL
    - name: ensure database exists
      become: yes
      become_user: postgres
      postgresql_db: 
        name: "{{ SHORT_NAME }}"
        # owner: "{{ SHORT_NAME }}"
    - name: ensure database user exists with permissions
      become: yes
      become_user: postgres
      postgresql_user: 
        db: "{{ SHORT_NAME }}"
        name: "{{ DATABASE_USER_PROD }}"
        password: "{{ DATABASE_PASSWORD_PROD }}"
        priv: ALL
        # role_attr_flags=CREATEDB,NOSUPERUSER




    # Django
    - name: copy source files
      synchronize:
        src: "{{ BASE_DIR_LOCAL }}/"
        dest: "{{ BASE_DIR }}"
      notify:
        - restart uwsgi
    - name: copy extra source files
      synchronize:
        src: "{{ BASE_DIR_EXTRAS_LOCAL }}/"
        dest: "{{ BASE_DIR_EXTRAS }}"
      notify:
        - restart uwsgi
    # - name: ensure git repository is up-to-date
    #   git: repo={{ REPO }} dest={{ BASE_DIR }} depth=1
    #   notify:
    #     - restart uwsgi
    #   # register: result
    # # - debug: var=result
    - name: ensure secrets file is present
      copy: src={{ BASE_DIR_LOCAL }}/secrets.json dest={{ BASE_DIR }}/secrets.json
    # - name: ensure python dependencies are present (to avoid hitting PyPi)
    #   copy: src=../dependencies dest={{ BASE_DIR }}
    # - name: ensure django uploaded directory exists
    #   file: path={{ BASE_DIR }}_uploads state=directory group=www-data mode="g+w" recurse=no
    # - name: ensure perms for log file
    #   file: path=/tmp/{{ SHORT_NAME }}.log state=touch group=www-data mode="g+w" 
    - name: ensure scripts are executable
      file: path={{ BASE_DIR }}/share/bin state=directory mode="u+x,g+x,o+x" recurse=yes
    - name: install python dependencies in virtualenv
      pip: 
        requirements: "{{ BASE_DIR }}/requirements.txt"
        virtualenv: "{{ VIRTUALENV }}"
        # extra_args: "-i ../dependencies"
        # executable: pip3
        virtualenv_python: python3
      notify:
        - restart uwsgi

    ## NGINX
    - name: ensure default nginx configuration is not present
      become: yes
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: ensure nginx 'available' configuration is present
      become: yes
      copy: src={{ BASE_DIR_LOCAL }}/share/conf/nginx.conf dest=/etc/nginx/sites-available/{{ SHORT_NAME }}
      notify:
        - restart nginx
    - name: ensure nginx 'enabled' configuration is present
      become: yes
      file: src=/etc/nginx/sites-available/{{ SHORT_NAME }} path=/etc/nginx/sites-enabled/{{ SHORT_NAME }} state=link
      # copy: src={{ BASE_DIR_LOCAL }}/share/conf/nginx.conf dest=/etc/nginx/sites-enabled/{{ SHORT_NAME }}
      notify:
        - restart nginx

    # - name: ensure nginx 'available' configuration is present for static sites
    #   become: yes
    #   template: src={{ BASE_DIR_LOCAL }}/share/conf/nginx-static.conf.j2 dest=/etc/nginx/sites-available/{{ item.cannonical_name }}
    #   with_items: "{{ STATIC_SITES }}"
    #   notify:
    #     - restart nginx
    # - name: ensure nginx 'enabled' configuration is present for static sites
    #   become: yes
    #   file: src=/etc/nginx/sites-available/{{ item.cannonical_name }} path=/etc/nginx/sites-enabled/{{ item.cannonical_name }} state=link
    #   with_items: "{{ STATIC_SITES }}"
    #   notify:
    #     - restart nginx



    ## uWSGI
    - name: ensure uwsgi configuration is present
      template: src={{ BASE_DIR_LOCAL }}/share/conf/uwsgi.ini.j2 dest={{ ETC_DIR }}/uwsgi-{{ SHORT_NAME }}.ini
      notify:
        - restart uwsgi
    - name: ensure uwsgi-supervisor configuration is present
      template: src={{ BASE_DIR_LOCAL }}/share/conf/supervisor/uwsgi.conf.j2 dest={{ ETC_DIR }}/supervisor/uwsgi-{{ SHORT_NAME }}.conf
      notify:
        - restart uwsgi

    # ## Celery
    # - name: ensure celery-supervisor configuration is present
    #   template: src={{ BASE_DIR_LOCAL }}/share/conf/supervisor/celery.conf.j2 dest={{ ETC_DIR }}/supervisor/celery-{{ SHORT_NAME }}.conf
    #   notify:
    #     - restart celery
    # - name: ensure flower-supervisor configuration is present
    #   template: src={{ BASE_DIR_LOCAL }}/share/conf/supervisor/flower.conf.j2 dest={{ ETC_DIR }}/supervisor/flower-{{ SHORT_NAME }}.conf
    #   notify:
    #     - restart flower


  handlers:
    - include: handlers/handlers.yml

- hosts: all
  gather_facts: False
  vars:
    BASE_DIR: /home/web/spaceawe
    BASE_DIR_LOCAL: "{{ lookup('env','UNAWE_BASE') }}spaceawe"
    VIRTUALENV: /home/web/.virtualenvs/spaceawe
    REPO: https://github.com/unawe/spaceawe.git
    LOG_DIR: /home/web/usr/log
    ETC_DIR: /home/web/usr/etc
  tasks:

    - name: running django deploy tasks
      django_manage:
        command: "{{ item }}"
        app_path: "{{ BASE_DIR }}"
        virtualenv: "{{ VIRTUALENV }}"
      with_items:
        - migrate
        - collectstatic
        # - rebuild_index --noinput
        # - rebuild_index
      environment:
        DJANGO_SETTINGS_CONFIG: PROD
